baseurl = "/"
languageCode = "en-us"
title = "Config Title"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "this is my description"
  cover = "images/cover.jpg"
  author = "Dario Fuzinato"
  authorlocation = "Berlin"
  authorwebsite = "https://fussinatto.com"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = ""
  RSSLink = ""
  githubName = "fussinatto"
  twitterName = "fussinatto"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "your_twitter"
